### ISSUE TITLE
OpenMotics service can't start anymore

### ISSUE THREAD

**Issue by khenderick** [openmotics/gateway#20]
When there are communication issues with the Master, the OpenMotics service seems to crash on startup.

```
2017-04-22 10:00:21,410 - openmotics - INFO - Starting TimeKeeper
Traceback (most recent call last):
  File "openmotics_service.py", line 145, in <module>
    main()
  File "openmotics_service.py", line 105, in main
    gateway_api = GatewayApi(master_communicator, power_communicator, power_controller)
  File "/opt/openmotics/python/gateway/gateway_api.py", line 101, in __init__
    self.__init_shutter_status()
  File "/opt/openmotics/python/gateway/gateway_api.py", line 238, in __init_shutter_status
    ret = self.__master_communicator.do_command(master_api.number_of_io_modules())
  File "/opt/openmotics/python/master/master_communicator.py", line 189, in do_command
    result = consumer.get(timeout).fields
  File "/opt/openmotics/python/master/master_communicator.py", line 468, in get
    raise CommunicationTimedOutException()
serial_utils.CommunicationTimedOutException
```

**Comment by khenderick** [comment]
We should make these initialisations optional (so the service at least starts) and if not properly executed, re-try them every few seconds.
